import type { StoredRun } from "./session";

/** Builds a shareable Markdown report of a complete analysis (screen 6). */
export function buildReport(run: StoredRun): string {
  const { profile, analysis, model, elapsedMs, candidateCount } = run;
  const { primary, alternatives, skillGap, roadmap, nextStep, risks, assumptions } =
    analysis;

  const lines: string[] = [];
  const push = (...text: string[]) => lines.push(...text);

  push(
    "# ProjectsForge — Project Analysis Report",
    "",
    `> Generated ${new Date().toLocaleString()} · model \`${model}\` · ` +
      `${(elapsedMs / 1000).toFixed(1)}s · ${candidateCount} candidate projects scored`,
    "",
    "## 1. Student profile",
    "",
    `- **Branch / year:** ${profile.branch}, ${profile.year}`,
    `- **Skills:** ${profile.skills.length > 0 ? profile.skills.join(", ") : "(none listed)"}`,
    `- **Interests:** ${profile.interests.join(", ")}`,
    `- **Career goal:** ${profile.careerGoal}`,
    `- **Available time:** ${profile.availableWeeks} weeks`,
    "",
    "## 2. Recommended project",
    "",
    `### ${primary.title}`,
    "",
    `**Match ${primary.matchScore}/100** · ${primary.difficulty} · ~${primary.estimatedWeeks} weeks · ` +
      primary.technologies.join(" / "),
    "",
    `**Why this project:** ${primary.whyMatched}`,
    "",
    "**Prerequisites:**",
    "",
    ...primary.prerequisites.map((item) => `- ${item}`),
    "",
    `**Next step:** ${nextStep}`,
    "",
    "## 3. Alternatives",
    "",
    ...alternatives.flatMap((alt) => [
      `### ${alt.title} (match ${alt.matchScore})`,
      "",
      `${alt.difficulty} · ~${alt.estimatedWeeks} weeks · ${alt.technologies.join(" / ")}`,
      "",
      alt.whyMatched,
      "",
    ]),
    "## 4. Skill gap",
    "",
    "### Already known",
    "",
    profile.skills.length > 0
      ? skillGap.alreadyKnown.map((s) => `- ${s}`).join("\n")
      : "- (no existing skills listed — plan starts from fundamentals)",
    "",
    "### Need to learn",
    "",
    ...skillGap.needToLearn.map((item) => `- **${item.skill}** (${item.priority}) — ${item.why}`),
    "",
    `## 5. ${profile.availableWeeks}-week roadmap`,
    "",
    ...roadmap.flatMap((week) => [
      `### Week ${week.week} — ${week.focus}`,
      "",
      `- **Learn:** ${week.learn.join(", ")}`,
      `- **Build:** ${week.build}`,
      `- **Deliverable:** ${week.deliverable}`,
      "",
    ]),
    "## 6. Honest caveats",
    "",
    "**Risks**",
    "",
    ...risks.map((risk) => `- ${risk}`),
    "",
    "**Assumptions**",
    "",
    ...assumptions.map((assumption) => `- ${assumption}`),
    "",
    "---",
    "",
    "_Generated by ProjectsForge — from project ideas to career-ready skills._",
  );

  return lines.join("\n");
}

/** Copies the report to the clipboard (with legacy fallback). */
export async function copyReport(run: StoredRun): Promise<boolean> {
  const text = buildReport(run);
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // fall through to the legacy path
  }
  try {
    const area = document.createElement("textarea");
    area.value = text;
    area.style.position = "fixed";
    area.style.opacity = "0";
    document.body.appendChild(area);
    area.select();
    const ok = document.execCommand("copy");
    area.remove();
    return ok;
  } catch {
    return false;
  }
}

/** Triggers a browser download of the report as Markdown. */
export function downloadReport(run: StoredRun): void {
  const blob = new Blob([buildReport(run)], {
    type: "text/markdown;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `projectsforge-${run.profile.branch.toLowerCase()}-${run.profile.year.replace(/\s+/g, "-")}-report.md`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
